### ISSUE TITLE
WASM Support

### ISSUE THREAD

**Issue by pilat** [cosmos72/gls#2]
Greetings,

I'm using your gls package and encountered an issue when building an app for the WASM platform.

Upon reviewing your `gomacro` project, I observed the [WASM stub](https://github.com/cosmos72/gomacro/blob/master/gls/api_wasm.go). It appears the stub was created under the assumption that goroutines don't operate on WASM due to its lack of thread support. However, as mentioned in [this StackOverflow post](https://stackoverflow.com/a/68736161) while WASM doesn't support threads, goroutines are fully functional there.

To address this, I crafted an [id_wasm.s](https://github.com/pilat/gls/blob/support-wasm/id_wasm.s) file, adopting content from `id_arm64.s`, which resolved the matter. Later, I identified a similar solution [here](https://github.com/timandy/routine/blob/main/g/asm_wasm.s).

I've assembled a demonstration through a simple WASM application, showcasing gls operating efficiently with WASM. The example is available at https://github.com/pilat/gls-wasm-test.

If it's of interest to you, I'm willing to open a PR here to integrate these changes, facilitating better support for the WASM platform.

**Comment by cosmos72** [comment]
That's definitely a welcome addition, thanks!
It will also help to add support for `GOOS=js GOARCH=wasm` target to [gomacro](https://github.com/cosmos72/gomacro/), which uses a private copy of this package.

Waiting for your pull request :)

**Comment by pilat** [comment]
Just wanted to say thank you for merging the PR for WASM support. It's working great for my needs, and I really appreciate your quick action on this!
